In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

import matplotlib.pyplot as plt

import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
amazon="..\\data\\raw\\Reviews.csv"
tweet="..\\data\\raw\\training.1600000.processed.noemoticon.csv"

### Preprocessing of amazon dataset

In [3]:
#loading the data
df_amazon = pd.read_csv(amazon)

In [4]:
df_amazon.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [5]:
df_amazon = df_amazon[["Text", "Score"]]

# Binary sentiment
df_amazon["label"] = df_amazon["Score"].apply(
    lambda x: 1 if x >= 4 else 0
)

df_amazon = df_amazon[["Text", "label"]]

df_amazon = df_amazon.dropna()

df_amazon = df_amazon.sample(10000, random_state=42)

df_amazon.head()

                                                     Text  label
165256  Having tried a couple of other brands of glute...      1
231465  My cat loves these treats. If ever I can't fin...      1
427827  A little less than I expected.  It tends to ha...      0
433954  First there was Frosted Mini-Wheats, in origin...      0
70260   and I want to congratulate the graphic artist ...      1

### preprocessing of tweets dataset

In [6]:
twitter_df = pd.read_csv(
    tweet,
    encoding="latin-1",
    header=None
)

In [7]:
twitter_df.head()

,0,1,2,3,4,5
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [8]:
twitter_df = twitter_df[[0, 5]]

twitter_df.columns = ["label", "Text"]

twitter_df["label"] = twitter_df["label"].map({
    0: 0,
    4: 1
})

twitter_df = twitter_df.dropna()

twitter_df = twitter_df.sample(10000, random_state=42)

twitter_df.head()

        label                                               Text
541200      0             @chrishasboobs AHHH I HOPE YOUR OK!!!
750         0  @misstoriblack cool , i have no tweet apps  fo...
766711      0  @TiannaChaos i know  just family drama. its la...
285055      0  School email won't open  and I have geography ...
705995      0                             upper airways problem

### Comparing processed and raw text

##### 1)Amazon

In [9]:
from src.preprocessing.textpreprocessing import (
    TextPreprocessor,
    PreprocessingConfig
)

processor = TextPreprocessor(
    PreprocessingConfig.for_reviews()
)

# preprocess text column
df = processor.process_dataframe(
    df=df_amazon,
    text_col="Text",
    out_col="clean_text"
)

print(df[["Text", "clean_text"]].head())

[food_reviews] preprocessing: 100%|██████████| 10000/10000 [00:10<00:00, 926.86it/s]

                                                     Text  \
165256  Having tried a couple of other brands of glute...
231465  My cat loves these treats. If ever I can't fin...
427827  A little less than I expected.  It tends to ha...
433954  First there was Frosted Mini-Wheats, in origin...
70260   and I want to congratulate the graphic artist ...

                                               clean_text
165256  tried couple brand glutenfree sandwich cooky b...
231465  cat love treat ever not find house pop top bol...
427827  little less expected tends muddy taste not exp...
433954  first frosted miniwheats original size frosted...
70260   want congratulate graphic artist putting entir...

##### 2)tweets

In [10]:
from src.preprocessing.textpreprocessing import (
    TextPreprocessor,
    PreprocessingConfig
)

processor = TextPreprocessor(
    PreprocessingConfig.for_tweets()
)

# preprocess text column
df = processor.process_dataframe(
    df=twitter_df,
    text_col="Text",
    out_col="clean_text"
)

print(df[["Text", "clean_text"]].head())

[twitter] preprocessing: 100%|██████████| 10000/10000 [00:01<00:00, 6864.72it/s]
52 rows produced empty strings after preprocessing.

                                                     Text  \
541200             @chrishasboobs AHHH I HOPE YOUR OK!!!
750     @misstoriblack cool , i have no tweet apps  fo...
766711  @TiannaChaos i know  just family drama. its la...
285055  School email won't open  and I have geography ...
705995                             upper airways problem

                                               clean_text
541200                                          ahhh hope
750                                  cool tweet apps razr
766711  know family drama lamehey next time hang kim g...
285055  school email not open geography stuff revise s...
705995                               upper airway problem

### Comparing different vectorization methods

#### 1) BOW

In [11]:
from src.vectorization.bow import BoWVectorizer
bow_vectorizer = BoWVectorizer(text_processor=processor)
X_amazon_bow = bow_vectorizer.fit_transform(df_amazon["clean_text"])
X_twitter_bow = bow_vectorizer.fit_transform(twitter_df["clean_text"])

In [12]:
print(X_amazon_bow.shape)
print(X_twitter_bow.shape)

(10000, 5000)
(10000, 5000)

#### 2)TF-IDF

In [13]:
from src.vectorization.tfidf import TFIDFVectorizer

tfidf_vectorizer = TFIDFVectorizer(text_processor=processor)
X_amazon_tfidf = tfidf_vectorizer.fit_transform(df_amazon["clean_text"])
X_twitter_tfidf = tfidf_vectorizer.fit_transform(twitter_df["clean_text"])
print(X_amazon_tfidf.shape)
print(X_twitter_tfidf.shape)

(10000, 5000)
(10000, 5000)

#### 3)bm-25

In [14]:
from src.vectorization.bm25 import BM25Vectorizer
bm25_vectorizer = BM25Vectorizer(text_processor=processor)
X_amazon_bm25 = bm25_vectorizer.fit(df_amazon["clean_text"])
X_twitter_bm25 = bm25_vectorizer.fit(twitter_df["clean_text"])

In [15]:
X_amazon_bm25.search("This product is great!", top_k=5)

(array([9127, 2358, 7898,    9,  123]),
 array([9.62166499, 6.64468248, 6.26701458, 6.25967173, 6.25967173]))

#### Embeddings

##### 1)Word2vec

In [16]:
from src.vectorization.embeddings import Embeddings
embeddings_vectorizer = Embeddings(embedding_type="word2vec",embedding_path=r"..\word2vec\GoogleNews-vectors-negative300.bin",vector_size=300,window=5,min_count=2,workers=4)
embeddings_vectorizer.load_embeddings()

In [17]:
vector = embeddings_vectorizer.most_similar("king")
print(vector)

[('kings', 0.7138045430183411), ('queen', 0.6510956883430481), ('monarch', 0.6413194537162781), ('crown_prince', 0.6204220056533813), ('prince', 0.6159993410110474)]

In [18]:
embeddings_vectorizer.train_embeddings(df_amazon["clean_text"])

In [19]:
print(
    embeddings_vectorizer.model.wv["good"]
)

[-1.60783514e-01  5.48837006e-01  2.82510202e-02  9.19658095e-02
 -1.64661482e-01 -6.25470877e-01  2.26332784e-01  1.16111779e+00
 -1.28765285e-01 -3.91811430e-01  2.00569451e-01 -5.19122422e-01
 -3.98725152e-01  3.96451317e-02 -1.84765771e-01 -3.94424409e-01
  4.66320276e-01  1.79410368e-01 -3.96327078e-02 -1.59432337e-01
  3.64675783e-02  7.17135370e-02  5.26190877e-01  3.51904303e-01
  3.58559638e-01 -8.19797441e-02 -4.04238939e-01 -3.52996551e-02
 -3.37035328e-01 -3.42885256e-01  3.60638678e-01 -1.83587641e-01
  3.23532701e-01  3.87037963e-01 -3.34840752e-02  2.50199884e-01
  3.47153991e-01 -6.01651847e-01  2.26844490e-01  2.79375523e-01
  2.12578494e-02  3.42702299e-01  1.09600760e-01 -7.23182380e-01
  4.00322407e-01  3.57334793e-01  4.58180271e-02  2.29016557e-01
  1.16526991e-01  3.67340118e-01  1.96327060e-01  1.75134823e-01
 -3.13654423e-01  5.36771752e-02 -5.68830185e-02  3.17653924e-01
  2.51523405e-01 -5.40973879e-02  3.40177745e-01  1.74026396e-02
 -2.50411272e-01  7.52054453e-02  9.00859013e-02  1.52095273e-01
  8.03390518e-02  2.34339461e-01 -3.22730184e-01 -1.25497147e-01
 -3.90502125e-01 -1.86748639e-01  1.29726037e-01  6.31330833e-02
  1.93751216e-01 -4.63242680e-01  1.83236241e-01  2.28378698e-02
 -1.77575454e-01 -2.34047666e-01 -1.98180974e-03  2.40218788e-01
 -7.91509673e-02 -4.17111188e-01  1.98758319e-02  1.04466832e+00
 -2.49919947e-03  1.52446896e-01 -3.45580816e-01 -2.48983070e-01
  6.87242448e-01  2.66589820e-01  3.92434001e-01 -1.48965105e-01
 -1.32481083e-01  9.82332155e-02  4.60361928e-01 -1.21368051e-01
  4.81804401e-01 -3.67201477e-01 -2.40855291e-01  3.98553982e-02
 -8.54757354e-02  3.31631243e-01  4.28682238e-01 -6.93953559e-02
  3.26814014e-03 -1.47832423e-01 -3.23191315e-01  3.90299439e-01
 -6.12548232e-01 -1.28640765e-02 -3.57088804e-01  9.30966809e-02
 -4.34483625e-02  1.17989749e-01  1.67349055e-01  1.72350779e-01
  1.39916644e-01  5.83304465e-01  3.07949007e-01 -8.83484900e-01
  1.20144174e-01  1.45014346e-01  1.80122122e-01 -1.52831122e-01
 -3.05302978e-01  1.50615007e-01 -9.71182138e-02 -5.03703713e-01
 -2.12413110e-02  3.77616525e-01  3.43051255e-01  1.74780309e-01
 -2.42347969e-03 -5.47506452e-01 -3.42785604e-02  1.01314679e-01
  6.41538650e-02  1.37224318e-02 -7.29931891e-02 -2.50642329e-01
  1.30163908e-01 -4.37414169e-01 -2.35865459e-01  2.34153382e-02
  1.75207611e-02 -7.06931829e-01 -1.45196185e-01 -5.69717884e-01
  9.23196971e-02 -2.04896051e-02 -1.49454385e-01 -6.19738042e-01
 -1.42300725e-01 -9.61017795e-03  1.15582205e-01 -4.22432422e-05
 -4.48616117e-01 -2.36202389e-01  5.03237434e-02  2.84346372e-01
  6.19337037e-02  1.63073704e-01 -5.64993434e-02  2.86391586e-01
 -2.09090471e-01  3.70764732e-01  2.36913022e-02 -3.02572668e-01
  8.46092124e-03  1.66707873e-01 -2.51107216e-01 -2.04258740e-01
 -2.28231424e-03  4.31387931e-01  1.57961652e-01  1.98553592e-01
  3.06539759e-02 -2.56117553e-01 -9.57453474e-02  1.25510693e-01
  4.27448638e-02  2.53229380e-01 -1.52697623e-01  3.16329747e-01
 -1.40786573e-01 -1.84271811e-03  4.61889595e-01  3.91829580e-01
 -8.50235969e-02 -2.75934488e-01  9.86106992e-02 -1.36634454e-01
  3.61324102e-01  2.91445982e-02 -5.45772575e-02 -7.56917149e-02
  1.68781325e-01 -1.24821119e-01 -7.99078774e-03 -1.05756752e-01
 -3.12139988e-01  4.01138812e-01 -4.57098931e-02  2.07240939e-01
 -1.11145750e-02 -1.93131402e-01  2.50886858e-01  2.54411519e-01
 -3.58121306e-01  8.02125707e-02 -3.11068624e-01 -2.16172934e-02
  2.78794527e-01 -1.67283386e-01  3.18706423e-01 -1.18801571e-01
 -1.98897555e-01 -4.40942287e-01 -4.08648610e-01 -2.56155789e-01
 -1.05005823e-01 -2.01715246e-01  1.40807003e-01 -1.98744163e-01
 -2.99318194e-01 -1.20310687e-01  1.80685166e-02 -1.50957257e-01
  2.28296965e-01  5.18190712e-02  6.38617799e-02 -1.84496328e-01
  1.31464619e-02 -1.56316720e-02 -1.29370242e-01  2.04750910e-01
 -1.15312099e-01  4.31307368e-02  2.07069471e-01 -5.95153153e-01
 -3.94312851e-02 -8.50520730e-02 -4.31357324e-01 -9.41269938e-03
 -2.73541380e-02 -4.48080838e-01  1.03302844e-01  5.16101718e-02
  1.37468008e-03  2.83597320e-01  2.31068105e-01  1.16621815e-02
  1.56632006e-01 -4.81291898e-02 -5.52392960e-01 -2.34765187e-01
  7.58645415e-01 -3.19183688e-03 -7.04218507e-01 -5.82358420e-01
  1.26199424e-01 -2.39579335e-01  1.86290175e-01 -5.59608102e-01
 -6.10213399e-01  4.26302403e-01  5.42226255e-01  3.87102664e-01
 -4.85687643e-01  1.02362700e-01 -4.39993024e-01  2.80017644e-01
 -2.21781403e-01  9.92626771e-02  2.76970327e-01  3.92787874e-01
  1.26220971e-01  1.51766613e-01 -5.84769368e-01 -6.59960136e-02
  7.77565315e-03  3.17171812e-01 -4.99578901e-02  2.45143399e-01
  2.65162617e-01 -1.91661835e-01 -5.89859009e-01  3.16937894e-01
  1.63683191e-01  2.31337503e-01  2.02609286e-01  2.85150945e-01
 -7.58844241e-02 -3.13726902e-01  2.14132100e-01  4.26994532e-01
 -1.40540659e-01 -4.55528259e-01  2.40480617e-01 -4.94560361e-01]

In [20]:
print(
    embeddings_vectorizer.model.wv.most_similar("good", topn=5)
)

[('great', 0.9240363836288452), ('pretty', 0.8982052803039551), ('looking', 0.8893091678619385), ('restricted', 0.8839259743690491), ('overall', 0.867035984992981)]

##### 2)Glove vectorizer

In [21]:
from src.vectorization.embeddings import Embeddings
embeddings_vectorizer = Embeddings(embedding_type="glove",embedding_path=r"..\glove.6B\glove.6B.50d.txt",vector_size=300,window=5,min_count=2,workers=4)
embeddings_vectorizer.load_embeddings()